Les2
ilchenkoss/yadro pull request #4
Opened 2024-04-06 10:41 UTC by ilchenkoss

Код рабочий, но очень уж грязный 😬
Почищу постепенно

2024-04-07 12:14 UTC, vbelogrudov requested changes
программа работает только с -o.  Структура получилась запутанной - в идеале pkg/xcd, pkg/database, pkg/words не должны друг о друге ничего знать. А связующая логика может быть, например, в пакете scraper.

2024-04-07 12:14 UTC, vbelogrudov commented on config.yaml
> +  db_path : "./pkg/database/"
обычно db_path и есть файл, просто полный путь

2024-04-07 12:14 UTC, vbelogrudov commented on pkg/xkcd/scrape.go
> +				data, badIDs = secondScrape(client, ID, badIDs, 3)
data, - is not used, можно _, badIDs =

2024-04-07 12:14 UTC, vbelogrudov commented on pkg/xkcd/scrape.go
> +	//response ok
выглядит сложно. Лучше спрятать retry в функцию sendRequest(url) (data, error) вместе с этой http-шной логикой

2024-04-07 12:14 UTC, vbelogrudov commented on pkg/xkcd/scrape.go
> +			} else if Condition == true {
else if Condition {

2024-04-07 12:14 UTC, vbelogrudov commented on pkg/xkcd/scrape.go
> +				badIDs[startID] = 1337 //parser error
1337, если это имеет смысл, должна быть константой

2024-04-07 13:12 UTC, ilchenkoss commented
Спасибо за ревью, все по делу ))

2024-04-07 21:54 UTC, ilchenkoss commented
Пересобрал зависимости, так явно лучше, спасибо.

2024-04-11 10:35 UTC, vbelogrudov approved these changes

2024-04-11 19:52 UTC, merged